apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: web-app
   labels:
     app: web-app
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: web-app
   template:
     metadata:
       labels:
         app: web-app
     spec:
       containers:
         - name: nginx
           image: nginx:latest
           ports:
             - containerPort: 80
           volumeMounts:
             - name: web-content
               mountPath: /usr/share/nginx/html
       volumes:
         - name: web-content
           configMap:
             name: web-content
 ---
 apiVersion: v1
 kind: Service
 metadata:
   name: web-app-service
 spec:
   type: NodePort
   selector:
     app: web-app
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
       nodePort: 30080  # Change this if needed
 ---
 apiVersion: v1
 kind: ConfigMap
 metadata:
   name: web-content
 data:
   index.html: |
 <!DOCTYPE html>
 <html>
 <head>
 <title>Welcome to ArgoCD!</title>
 <style>
         body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
 </style>
 </head>
 <body>
 <h1>Deployed via ArgoCD 🎉</h1>
 <p>This is a simple web page running on Nginx!</p>
 </body>
 </html>
